import { Question, QuestionType } from '../types';

const textDiritto = `Il Processo Legislativo in Italia: Guida all'Iter di Approvazione delle Leggi

Introduzione

La funzione legislativa rappresenta uno dei pilastri fondamentali su cui si regge la democrazia italiana, incarnando il principio della separazione dei poteri. È attraverso l'emanazione delle leggi che vengono definite le regole della convivenza civile, garantiti i diritti dei cittadini e delineate le politiche pubbliche. In questo assetto, il Parlamento assume un ruolo di assoluta centralità, essendo l'organo costituzionale depositario di tale funzione.

1. L'Architettura del Potere Legislativo: Il Parlamento Italiano

Il sistema parlamentare italiano è caratterizzato dal principio del bicameralismo perfetto. Ciò significa che il Parlamento è composto da due Camere, la Camera dei Deputati e il Senato della Repubblica, che possiedono poteri e funzioni perfettamente identici. Ogni legge, per essere approvata, deve ottenere il consenso di entrambe le assemblee sullo stesso identico testo. L'aggettivo "stesso" deve essere inteso nel suo significato più stringente: il testo approvato deve essere "identico anche nelle virgole". A seguito del referendum costituzionale del settembre 2020, il numero dei parlamentari è stato ridotto, passando da 630 a 400 deputati e da 315 a 200 senatori elettivi. Oltre ai membri elettivi, il Senato della Repubblica include la figura dei Senatori a vita (ex Presidenti della Repubblica di diritto, e fino a 5 cittadini nominati dal Presidente in carica per altissimi meriti).

2. L'Iter Legis Ordinario: Il Percorso di una Legge

2.1. Fase 1: L'Iniziativa Legislativa
Il processo prende avvio con la presentazione di un "progetto di legge". I soggetti abilitati sono: il Governo, ciascun parlamentare, 50.000 elettori (iniziativa popolare), le Regioni, e il CNEL.

2.2. Fase 2: La Discussione e la Votazione
Il progetto viene assegnato alla Commissione competente per materia che lavora in sede referente, esaminando il testo e redigendo una relazione per l'intera assemblea. Successivamente, la Camera discute e vota il testo "articolo per articolo", con la possibilità di proporre "emendamenti" (modifiche). Se approvato, il testo passa all'altra Camera. Se questa lo modifica, il testo deve tornare indietro ("navetta" o "spola") finché entrambe non approvano un testo identico.

2.3. Fase 3: La Promulgazione
Il testo approvato passa al Presidente della Repubblica per un controllo di legittimità costituzionale. Se conforme, lo firma (promulgazione). Se ravvisa contrasti con la Costituzione, può esercitare il "diritto di veto sospensivo", rinviando la legge alle Camere con un messaggio motivato. Se le Camere la riapprovano identica, il Presidente è obbligato a promulgarla.

2.4. Fase 4: La Pubblicazione e l'Entrata in Vigore
La legge viene pubblicata sulla Gazzetta Ufficiale. Di norma, entra in vigore dopo 15 giorni (vacatio legis), per permetterne la conoscibilità.

3. L'Iter Legis Aggravato: A Tutela della Costituzione Rigida

Per modificare la Costituzione (che è "rigida") serve un iter aggravato. Le differenze principali sono:
- Doppia deliberazione: Ogni Camera approva il testo due volte, con un intervallo non inferiore a tre mesi tra la prima e la seconda votazione.
- Maggioranze qualificate: Nella seconda votazione, se si ottiene la maggioranza dei 2/3 dei componenti di ciascuna Camera, la legge è approvata. Se si ottiene solo la maggioranza assoluta (50%+1), la legge viene pubblicata ma entro tre mesi può essere richiesto un referendum confermativo da parte di 500.000 elettori, 5 Consigli Regionali o 1/5 dei parlamentari. Se il referendum è richiesto, l'esito popolare è decisivo. Altrimenti, la legge è approvata tacitamente.`;

const textMortati = `«Uno Stato concreto non può pensarsi esistente se non come organizzazione giuridica di una collettività ordinata secondo un’idea politica. Il popolo, preso nella sua generalità, non può fornire il principio generale di unificazione che valga a comporre gli interessi contrastanti e ad avviare lo Stato verso una meta determinata. Tale scopo deve porsi come la fonte prima di qualificazione, il criterio che presiede alla giurisdizione dei rapporti sociali. Quando la legge fondamentale sorge sulla base di compromessi fra principi opposti, la prevalenza che una delle forze riesca ad ottenere sull’altra, e il conseguente mutamento del modo di funzionare della costituzione originaria, devono considerarsi come espressione dell’instaurazione di un ordine diverso.»
(Costantino Mortati, "La Costituzione in senso materiale")`;

export const dirittoQuestions: Question[] = [
  // --- 1. DOMANDE SU TESTO "PROCESSO LEGISLATIVO" ---
  { id: "dir-01", type: QuestionType.MULTIPLE_CHOICE, topic: "Architettura Costituzionale", contextText: textDiritto, text: "Cosa si intende con l'espressione 'bicameralismo perfetto' nel sistema parlamentare italiano?", options: [ "Che la Camera dei Deputati ha poteri superiori al Senato.", "Che le due Camere hanno funzioni diverse e specializzate.", "Che Camera e Senato possiedono poteri e funzioni identici e ogni legge deve essere approvata da entrambe nello stesso identico testo.", "Che il numero totale dei parlamentari è stato ridotto a 600." ], correctAnswerIndex: 2, explanation: "Il testo definisce il bicameralismo perfetto come il sistema in cui le due Camere 'possiedono poteri e funzioni perfettamente identici' e una legge deve ottenere il consenso di entrambe 'sullo stesso identico testo'." },
  { id: "dir-02", type: QuestionType.MULTIPLE_CHOICE, topic: "Iter Legislativo Ordinario", contextText: textDiritto, text: "Durante la discussione di un progetto di legge in aula, quale strumento permette ai parlamentari di proporre modifiche al testo?", options: [ "Il veto sospensivo", "La promulgazione", "L'emendamento", "La navetta parlamentare" ], correctAnswerIndex: 2, explanation: "Il testo specifica che durante la discussione articolo per articolo, i parlamentari possono proporre modifiche definite tecnicamente 'emendamenti'." },
  { id: "dir-03", type: QuestionType.MULTIPLE_CHOICE, topic: "Ruolo del Presidente della Repubblica", contextText: textDiritto, text: "Cosa accade se il Presidente della Repubblica esercita il suo 'diritto di veto sospensivo' su una legge e le Camere la approvano nuovamente senza modifiche?", options: [ "La legge viene definitivamente bloccata.", "Il Presidente è obbligato a promulgarla.", "La legge viene sottoposta a referendum popolare.", "La questione viene decisa dalla Corte Costituzionale." ], correctAnswerIndex: 1, explanation: "Il testo chiarisce che il potere di veto del Presidente ha un limite: 'se le Camere approvano nuovamente la legge senza modifiche, il Presidente è obbligato a promulgarla'." },
  { id: "dir-04", type: QuestionType.MULTIPLE_CHOICE, topic: "Entrata in Vigore", contextText: textDiritto, text: "Che cos'è la 'vacatio legis' e qual è la sua durata standard?", options: [ "Il periodo di discussione in Commissione, dura un mese.", "L'intervallo di 3 mesi tra le due votazioni per le leggi costituzionali.", "Il periodo di 15 giorni tra la pubblicazione di una legge sulla Gazzetta Ufficiale e la sua entrata in vigore.", "Il tempo a disposizione del Presidente per promulgare una legge, dura 30 giorni." ], correctAnswerIndex: 2, explanation: "La 'vacatio legis' è definita nel testo come l'intervallo di tempo, di norma 15 giorni, tra la pubblicazione e l'entrata in vigore della legge per garantirne la conoscibilità." },
  { id: "dir-05", type: QuestionType.MULTIPLE_CHOICE, topic: "Iter Legislativo Aggravato", contextText: textDiritto, text: "In quali circostanze può essere richiesto un referendum confermativo per una legge di revisione costituzionale?", options: [ "Sempre, per ogni legge costituzionale.", "Solo se il Presidente della Repubblica lo richiede.", "Se la legge è approvata nella seconda deliberazione con una maggioranza dei 2/3 dei componenti.", "Se la legge è approvata nella seconda deliberazione con la sola maggioranza assoluta." ], correctAnswerIndex: 3, explanation: "Il testo spiega che il referendum può essere richiesto se il progetto è approvato 'con la sola maggioranza assoluta (50%+1 dei componenti)' e non con la maggioranza più alta dei 2/3." },
  { id: "dir-06", type: QuestionType.MULTIPLE_CHOICE, topic: "Iniziativa Legislativa", contextText: textDiritto, text: "Quale dei seguenti soggetti NON ha il potere di iniziativa legislativa secondo la Costituzione?", options: [ "Il Governo", "Ciascun parlamentare", "I Presidenti delle Province", "50.000 elettori" ], correctAnswerIndex: 2, explanation: "Il testo elenca i cinque soggetti abilitati all'iniziativa legislativa: Governo, parlamentari, 50.000 elettori, Regioni, CNEL. I Presidenti delle Province non sono inclusi." },
  { id: "dir-07", type: QuestionType.MULTIPLE_CHOICE, topic: "Architettura Costituzionale", contextText: textDiritto, text: "A seguito del referendum del 2020, il numero dei parlamentari elettivi è stato fissato a:", options: [ "630 deputati e 315 senatori", "400 deputati e 200 senatori", "500 deputati e 250 senatori", "400 deputati e 315 senatori" ], correctAnswerIndex: 1, explanation: "Il testo riporta esplicitamente la riduzione del numero dei parlamentari, 'passando da 630 a 400 deputati e da 315 a 200 senatori elettivi'." },
  { id: "dir-08", type: QuestionType.MULTIPLE_CHOICE, topic: "Iter Legislativo Ordinario", contextText: textDiritto, text: "Il passaggio di un progetto di legge tra le due Camere finché non si approva un testo identico è chiamato:", options: [ "Iter aggravato", "Vacatio legis", "Veto sospensivo", "Navetta o spola" ], correctAnswerIndex: 3, explanation: "Il testo definisce questo passaggio come 'noto come \"navetta\" o \"spola\"'." },
  { id: "dir-09", type: QuestionType.MATRIX, topic: "Funzioni e Fasi (Vero/Falso)", contextText: textDiritto, text: "Indica se le seguenti affermazioni sul processo legislativo sono vere o false.", matrixRows: [ "L'età minima per essere eletti al Senato è 25 anni.", "Una legge approvata solo dalla Camera dei Deputati può entrare in vigore in casi di urgenza.", "Le Commissioni parlamentari esaminano il progetto di legge prima dell'intera assemblea.", "Nell'iter aggravato, l'intervallo tra le due votazioni deve essere di almeno tre mesi.", "Tutti gli ex Presidenti della Repubblica diventano Senatori a vita di diritto." ], matrixCols: [ "Vero", "Falso" ], matrixCorrectAnswer: [1, 1, 0, 0, 0], explanation: "Età Senato 40 anni (F). Una legge deve essere approvata da entrambe le Camere (F). Le Commissioni lavorano in sede referente prima dell'aula (V). Intervallo di 3 mesi per iter aggravato (V). Ex Presidenti sono senatori a vita (V)." },
  { id: "dir-10", type: QuestionType.MATRIX, topic: "Attori e Ruoli", contextText: textDiritto, text: "Associa ciascun soggetto o organo alla sua funzione principale nell'iter legislativo descritto.", matrixRows: [ "Governo", "Commissione permanente", "Presidente della Repubblica", "Gazzetta Ufficiale" ], matrixCols: [ "Iniziativa", "Esame referente", "Controllo di legittimità", "Pubblicazione" ], matrixCorrectAnswer: [0, 1, 2, 3], explanation: "Il Governo ha potere di iniziativa. La Commissione esamina il testo in sede referente. Il Presidente effettua il controllo di legittimità e promulga. La Gazzetta Ufficiale serve per la pubblicazione e la conoscibilità della legge." },

  // --- 2. DOMANDE SU TESTO DI C. MORTATI (Nuovi Inserimenti) ---
  { id: "dir-mortati-01", type: QuestionType.MULTIPLE_CHOICE, topic: "Dottrina Costituzionale", contextText: textMortati, text: "Secondo il testo, cosa permette di 'comporre gli interessi contrastanti' in uno Stato?", options: ["La buona volontà di ogni singolo cittadino.", "Un principio di unificazione (idea politica) portato avanti da forze organizzate.", "Il ritorno alle leggi del Medioevo.", "La decisione unilaterale del Re."], correctAnswerIndex: 1, explanation: "Mortati afferma che il popolo da solo non basta, serve un'idea politica organizzata per unificare e dirigere lo Stato." },
  { id: "dir-mortati-02", type: QuestionType.MULTIPLE_CHOICE, topic: "Dottrina Costituzionale", contextText: textMortati, text: "Cosa accade, secondo Mortati, quando una forza politica prevale su un'altra in un sistema basato su compromessi?", options: ["Si torna semplicemente alla situazione precedente.", "La Costituzione scritta viene bruciata.", "Si assiste all'instaurazione di un ordine politico e sociale diverso.", "Lo Stato smette di esistere giuridicamente."], correctAnswerIndex: 2, explanation: "Il testo dice che la prevalenza di una forza e il mutamento del funzionamento costituzionale sono 'espressione dell’instaurazione di un ordine diverso'." },
  { id: "dir-mortati-03", type: QuestionType.MULTIPLE_CHOICE, topic: "Dottrina Costituzionale", contextText: textMortati, text: "Perché il 'popolo preso nella sua generalità' non è sufficiente a creare la Costituzione materiale?", options: ["Perché i cittadini non conoscono il diritto.", "Perché il popolo non ha diritto di voto.", "Perché non può fornire da solo un obiettivo unitario e una direzione politica precisa.", "Perché Mortati non credeva nella democrazia."], correctAnswerIndex: 2, explanation: "Mortati scrive che il popolo 'non può fornire il principio generale di unificazione che valga a comporre gli interessi contrastanti'." },
  { id: "dir-mortati-04", type: QuestionType.MULTIPLE_CHOICE, topic: "Dottrina Costituzionale", contextText: textMortati, text: "Qual è la 'parte costitutiva' essenziale di uno Stato concreto?", options: ["Il territorio geografico e i suoi confini.", "Una collettività ordinata secondo un'idea politica.", "Esclusivamente il testo scritto della Costituzione.", "Il sistema delle sanzioni penali."], correctAnswerIndex: 1, explanation: "Lo Stato esiste come 'organizzazione giuridica di una collettività ordinata secondo un’idea politica'." },
  { id: "dir-mortati-05", type: QuestionType.MULTIPLE_CHOICE, topic: "Dottrina Costituzionale", contextText: textMortati, text: "In che modo questo brano aiuta a capire la nascita della Costituzione italiana del 1948?", options: ["Spiega che è stata scritta da un solo partito vincitore.", "Inquadra il testo come il risultato del compromesso tra forze (cattoliche, marxiste, liberali) che hanno stabilito un nuovo ordine.", "Dimostra che la Costituzione del 1948 è identica allo Statuto Albertino.", "Dice che i partiti politici non hanno avuto alcun ruolo nel 1946"], correctAnswerIndex: 1, explanation: "Il riferimento ai 'compromessi fra principi opposti' riflette la natura pattizia della Costituzione italiana, nata dall'accordo tra le grandi forze politiche antifasciste." },

  // --- 3. DOMANDE DI CULTURA GIURIDICA GENERALE (Nuovi Inserimenti) ---
  { id: "dir-gen-01", type: QuestionType.MULTIPLE_CHOICE, topic: "Storia Costituzionale", text: "Cosa si intende per 'operazione gattopardesca' in riferimento alla concessione dello Statuto Albertino?", options: ["Una riforma che introduce la democrazia diretta.", "Un cambiamento formale della struttura dei poteri per far sì che, nella sostanza, il potere restasse nelle mani del Re.", "Un accordo segreto tra il Re e Garibaldi.", "La decisione di abolire la monarchia a favore della repubblica."], correctAnswerIndex: 1, explanation: "L'espressione si riferisce al motto 'tutto cambi perché nulla cambi', indicando una costituzione formale che manteneva il potere sostanziale al Sovrano." },
  { id: "dir-gen-02", type: QuestionType.MULTIPLE_CHOICE, topic: "Storia Costituzionale", text: "Chi era Filomena Delli Castelli, citata spesso durante le lezioni?", options: ["La prima donna a ricoprire la carica di Presidente del Consiglio.", "Una delle 21 donne elette nell'Assemblea Costituente, legata storicamente all'Istituto Magistrale di Città Sant'Angelo.", "Una senatrice a vita nominata per meriti scientifici.", "La regina che guidò l'Italia durante la fase di transizione nel 1946."], correctAnswerIndex: 1, explanation: "Fu una delle 21 'Madri Costituenti', insegnante e politica italiana." },
  { id: "dir-gen-03", type: QuestionType.MULTIPLE_CHOICE, topic: "Principi Fondamentali", text: "Secondo l'Articolo 5 della Costituzione, in che modo la Repubblica attua il 'decentramento amministrativo'?", options: ["Trasferendo la capitale da Roma ad altre città regionali.", "Delegando parte delle funzioni dello Stato agli enti locali come Comuni, Province e Regioni.", "Abolendo le leggi nazionali a favore di quelle comunali.", "Impedendo alle Regioni di avere autonomia finanziaria."], correctAnswerIndex: 1, explanation: "L'Art. 5 afferma che la Repubblica 'attua nei servizi che dipendono dallo Stato il più ampio decentramento amministrativo'." },
  { id: "dir-gen-04", type: QuestionType.MULTIPLE_CHOICE, topic: "Rapporti Stato-Chiesa", text: "Ai sensi dell'Articolo 7, quando è possibile modificare i Patti Lateranensi senza ricorrere a una legge di revisione costituzionale?", options: ["Ogni volta che il Governo lo ritiene necessario per motivi di bilancio.", "Solo se il Papa decide autonomamente di cambiarli.", "Se le modificazioni sono accettate sia dallo Stato che dalla Chiesa cattolica.", "Se viene indetto un referendum abrogativo popolare."], correctAnswerIndex: 2, explanation: "L'Art. 7 stabilisce che le modificazioni dei Patti, se 'accettate dalle due parti', non richiedono procedimento di revisione costituzionale." },
  { id: "dir-gen-05", type: QuestionType.MULTIPLE_CHOICE, topic: "Parlamento", text: "Chi sono i senatori a vita 'di diritto' secondo l'ordinamento italiano?", options: ["I cittadini che hanno vinto una medaglia d'oro alle Olimpiadi.", "Gli ex Presidenti della Repubblica, salvo rinuncia.", "I cinque cittadini nominati dal Presidente del Consiglio per meriti letterari.", "Tutti i membri della Commissione di 75 deputati che scrissero la Costituzione."], correctAnswerIndex: 1, explanation: "L'Art. 59 prevede che sia senatore di diritto e a vita, salvo rinunzia, 'chi è stato Presidente della Repubblica'." },
  { id: "dir-gen-06", type: QuestionType.MULTIPLE_CHOICE, topic: "Governo", text: "Cosa succede durante la fase di formazione del Governo quando il Presidente incaricato accetta 'con riserva'?", options: ["Deve dimettersi immediatamente e lasciare il posto a un altro candidato.", "Avvia consultazioni proprie con le forze politiche per verificare se avrà la maggioranza e concordare la lista dei ministri.", "Giura fedeltà alla Costituzione prima ancora di conoscere i suoi ministri.", "Viene eletto automaticamente dal popolo tramite un voto elettronico."], correctAnswerIndex: 1, explanation: "L'accettazione con riserva permette al Presidente incaricato di svolgere le consultazioni per verificare la fattibilità politica del governo prima di sciogliere la riserva." },
  { id: "dir-gen-07", type: QuestionType.MULTIPLE_CHOICE, topic: "Iter Legislativo", text: "Secondo l'iter legis ordinario, chi deve presentare il decreto-legge alle Camere per la conversione?", options: ["Il Presidente della Repubblica, entro 15 giorni.", "Il Governo, il giorno stesso della sua pubblicazione.", "La Magistratura, dopo averne verificato la costituzionalità.", "Almeno 50.000 elettori tramite petizione."], correctAnswerIndex: 1, explanation: "L'Art. 77 obbliga il Governo a presentare il decreto alle Camere per la conversione 'il giorno stesso' della sua emanazione." },
  { id: "dir-gen-08", type: QuestionType.MULTIPLE_CHOICE, topic: "Fonti del Diritto", text: "Quali vincoli deve rispettare il Governo quando emana un decreto legislativo?", options: ["Può legiferare liberamente su qualsiasi materia senza limiti di tempo.", "Deve attenersi ai principi, all'oggetto (argomento) e ai tempi stabiliti dal Parlamento nella 'legge delega'.", "Deve ottenere preventivamente il parere favorevole della Corte Costituzione.", "Può emanarlo solo se è stato indetto un referendum confermativo."], correctAnswerIndex: 1, explanation: "Il decreto legislativo è un atto avente forza di legge emanato dal Governo su delega del Parlamento, che fissa principi, criteri direttivi, tempo e oggetto (Art. 76)." },
  { id: "dir-gen-09", type: QuestionType.MULTIPLE_CHOICE, topic: "Iter Costituzionale", text: "Nel procedimento di revisione costituzionale (Art. 138), qual è l'intervallo minimo tra la prima e la seconda deliberazione di ciascuna Camera?", options: ["Quindici giorni.", "Sessanta giorni.", "Non meno di tre mesi.", "Un anno solare completo."], correctAnswerIndex: 2, explanation: "L'Art. 138 prescrive un intervallo non minore di tre mesi tra le due deliberazioni per garantire una riflessione adeguata." },
  { id: "dir-gen-10", type: QuestionType.MULTIPLE_CHOICE, topic: "Dottrina Costituzionale", text: "Nel pensiero di Costantino Mortati, cos'è che determina la 'costituzione in senso materiale'?", options: ["Il semplice testo scritto approvato dall'Assemblea Costituente.", "L'ordine politico e sociale imposto dalle forze politiche dominanti che riescono a imporre un indirizzo stabile alla comunità.", "L'insieme dei codici penali e civili ereditati dal periodo fascista.", "La volontà del popolo preso nella sua generalità astratta."], correctAnswerIndex: 1, explanation: "La costituzione materiale è l'insieme dei fini e dei valori fondamentali portati avanti dalle forze politiche dominanti in un dato momento storico." },

  // --- 4. DOMANDE EXTRA (Mantenute da inserimenti precedenti per completezza) ---
  { id: "dir-hist-05", type: QuestionType.MULTIPLE_CHOICE, topic: "Storia Costituzionale", text: "Quante donne furono elette nell'Assemblea Costituente il 2 giugno 1946?", options: ["556", "75", "21", "9"], correctAnswerIndex: 2, explanation: "Solo 21 donne furono elette su un totale di 556 membri, un passo storico importante ma numericamente ridotto." },
  { id: "dir-hist-06", type: QuestionType.MULTIPLE_CHOICE, topic: "Storia Costituzionale", text: "Quale caratteristica dello Statuto Albertino permise a Mussolini di stravolgerlo facilmente?", options: ["La sua lunghezza.", "La sua rigidità.", "La sua flessibilità, essendo modificabile con legge ordinaria.", "Il fatto di essere una costituzione votata."], correctAnswerIndex: 2, explanation: "Lo Statuto Albertino era una costituzione 'flessibile', cioè modificabile con una legge ordinaria, permettendo al regime fascista di alterare l'ordinamento senza procedure speciali." },
  { id: "dir-hist-07", type: QuestionType.MULTIPLE_CHOICE, topic: "Storia Costituzionale", text: "Cosa si intende con l'espressione 'Costituzione ottriata'?", options: ["Una costituzione approvata dal popolo tramite referendum.", "Una costituzione concessa unilateralmente dal sovrano.", "Una costituzione rigida che non può essere mai modificata.", "Una costituzione scritta da una commissione di esperti stranieri."], correctAnswerIndex: 1, explanation: "'Ottriata' deriva dal francese 'octroyée', che significa concessa dall'alto (dal sovrano) ai sudditi, non votata da un'assemblea." },
  { id: "dir-princ-08", type: QuestionType.MULTIPLE_CHOICE, topic: "Principi Fondamentali", text: "Secondo l'Articolo 1 della Costituzione, a chi appartiene la sovranità?", options: ["Al Presidente della Repubblica.", "Al Parlamento, che la esercita senza limiti.", "Al popolo, che la esercita nelle forme e nei limiti della Costituzione.", "Alle forze armate, per garantire la sicurezza nazionale."], correctAnswerIndex: 2, explanation: "L'Art. 1 comma 2 recita: 'La sovranità appartiene al popolo, che la esercita nelle forme e nei limiti della Costituzione'." },
  { id: "dir-princ-09", type: QuestionType.MULTIPLE_CHOICE, topic: "Principi Fondamentali", text: "Qual è la differenza principale tra uguaglianza formale e uguaglianza sostanziale (Art. 3)?", options: ["Non c'è differenza, sono due modi per dire la stessa cosa.", "L'uguaglianza formale riguarda solo gli uomini, quella sostanziale le donne.", "L'uguaglianza formale afferma che siamo tutti uguali davanti alla legge; quella sostanziale impegna lo Stato a rimuovere gli ostacoli che impediscono tale uguaglianza.", "L'uguaglianza sostanziale è valida solo in ambito economico."], correctAnswerIndex: 2, explanation: "Il comma 1 sancisce l'uguaglianza formale (davanti alla legge), il comma 2 quella sostanziale (rimozione degli ostacoli economico-sociali)." },
  { id: "dir-princ-10", type: QuestionType.MULTIPLE_CHOICE, topic: "Principi Fondamentali", text: "Cosa stabilisce l'Articolo 11 riguardo alla guerra?", options: ["L'Italia può dichiarare guerra per espandere i propri confini.", "L'Italia ripudia la guerra come strumento di offesa alla libertà degli altri popoli.", "L'Italia può usare la guerra per risolvere qualsiasi controversia internazionale.", "La guerra è ammessa solo se approvata dal Presidente della Repubblica senza limiti."], correctAnswerIndex: 1, explanation: "L'Art. 11 afferma: 'L'Italia ripudia la guerra come strumento di offesa alla libertà degli altri popoli e come mezzo di risoluzione delle controversie internazionali'." },
  { id: "dir-gov-11", type: QuestionType.MULTIPLE_CHOICE, topic: "Governo", text: "Chi nomina il Presidente del Consiglio dei Ministri?", options: ["Il popolo durante le elezioni politiche.", "Il Parlamento in seduta comune.", "Il Presidente della Repubblica.", "Il segretario del partito che ha ottenuto più voti."], correctAnswerIndex: 2, explanation: "Secondo l'Art. 92, 'Il Presidente della Repubblica nomina il Presidente del Consiglio dei Ministri e, su proposta di questo, i Ministri'." },
  { id: "dir-gov-12", type: QuestionType.MULTIPLE_CHOICE, topic: "Governo", text: "Cosa deve fare il Governo entro 10 giorni dalla sua nomina?", options: ["Emanare il primo decreto-legge di urgenza.", "Presentarsi alle Camere per esporre il programma e ottenere la fiducia.", "Sciogliere il Parlamento se non è d'accordo con i ministri scelti.", "Nominare i senatori a vita."], correctAnswerIndex: 1, explanation: "Art. 94: 'Entro dieci giorni dalla sua formazione il Governo si presenta alle Camere per ottenerne la fiducia'." },
  { id: "dir-gov-13", type: QuestionType.MULTIPLE_CHOICE, topic: "Governo", text: "Qual è la funzione principale del Consiglio dei Ministri?", options: ["Interpretare le leggi come la Magistratura.", "È l'organo deliberante che decide la politica generale del Governo.", "Scrivere i romanzi storici per le scuole.", "Approvare definitivamente le leggi costituzionali senza il Parlamento."], correctAnswerIndex: 1, explanation: "Il Consiglio dei Ministri determina la politica generale del Governo e l'indirizzo politico-amministrativo." },
  { id: "dir-gov-14", type: QuestionType.MULTIPLE_CHOICE, topic: "Governo", text: "Cosa succede se un decreto-legge non viene convertito in legge dal Parlamento entro 60 giorni?", options: ["Rimane in vigore ma perde d'importanza.", "Diventa una legge ordinaria a tempo indeterminato.", "Perde efficacia sin dall'inizio (effetti retroattivi).", "Il Governo può ripresentarlo identico il giorno dopo."], correctAnswerIndex: 2, explanation: "Art. 77: Se non convertiti entro 60 giorni, i decreti 'perdono efficacia sin dall'inizio' (decadenza ex tunc)." },
  { id: "dir-imm-19", type: QuestionType.MULTIPLE_CHOICE, topic: "Immunità Parlamentari", text: "Cosa garantisce l'insindacabilità ai parlamentari (Art. 68)?", options: ["Che non possono essere arrestati per nessun motivo.", "Che non possono essere perseguiti per le opinioni espresse e i voti dati nell'esercizio delle funzioni.", "Che possono offendere chiunque sui social senza rischi, anche fuori dalle funzioni.", "Che il loro stipendio non può essere tassato."], correctAnswerIndex: 1, explanation: "L'insindacabilità copre le opinioni espresse e i voti dati 'nell'esercizio delle funzioni', per garantire la libertà di espressione politica." },
  { id: "dir-imm-20", type: QuestionType.MULTIPLE_CHOICE, topic: "Immunità Parlamentari", text: "In quale caso un parlamentare può essere arrestato senza l'autorizzazione della Camera?", options: ["In nessun caso, l'immunità è assoluta.", "Se viene colto in flagranza di un reato per cui è previsto l'arresto obbligatorio o in caso di sentenza definitiva.", "Se il Presidente della Repubblica dà il suo consenso verbale.", "Solo se commette un reato durante le vacanze estive."], correctAnswerIndex: 1, explanation: "L'autorizzazione non è necessaria in esecuzione di una sentenza irrevocabile di condanna o se il parlamentare è colto nell'atto di commettere un reato (flagranza)." }
];