import { Question, QuestionType } from '../types';

const textBluePlanet = `OUR BLUE PLANET AND THE FUTURE\n\nParagraph A\nIn the framework of Agenda 2030, environmental protection has become a priority for students and citizens worldwide. We often discuss how to reduce our ecological footprint through small, everyday actions. For instance, rather than taking a long bath, choosing a quick shower is a practical way to avoid wasting water. Similarly, switching off lights and managing garbage items correctly helps in reducing waste and saving energy.\n\nParagraph B\nTo understand the beauty and the fragility of our world, many people watch the famous BBC documentary series, Blue Planet 2. This production was a massive effort, involving four years of work and 6,000 hours of underwater filming. Narrated by the legendary Sir David Attenborough, the series covers different habitats, such as coral reefs and the deep ocean, inspiring viewers to care for the sea.\n\nParagraph C\nThe series reveals that marine creatures are much more intelligent than we previously thought. For example, the giant trevally is a fish that can actually jump out of the water to catch and eat sea birds. Another fascinating creature is the tuskfish, which uses its mouth to hit molluscs against coral reefs until they break, allowing the fish to eat them. Even dolphins are shown enjoying themselves by surfing on waves.\n\nParagraph D\nDespite this beauty, there is a "terrible magic" threatening the oceans: plastic pollution. This is a dramatic warning for humanity. Every day, tons of plastic waste enter the sea, impacting every level of marine life. Increasing awareness about this issue is essential to finding a solution and protecting biodiversity.\n\nParagraph E\nOne solution is the transition to renewable resources. Sources such as wind power and solar energy are clean and easy to use in many countries. Other options include geothermal energy, which comes from the heat inside the ground, or biomass, which uses organic waste like wood or plants. However, burning biomass can sometimes create a little smoke, which is a small disadvantage for the environment.\n\nParagraph F\nUltimately, it is our collective responsibility to protect the planet. We must combine technological solutions with a change in our personal habits. If we do not act now, the consequences for future generations will be severe.`;

const scriptTeenMentalHealth = `Host: Good morning listeners, and welcome back to "Future Minds". Today we are diving into a topic that touches almost every family: the impact of social media on teenage mental health. Joining us is Dr. Sarah Jenkins, a child psychologist. Welcome, Sarah.
Dr. Jenkins: Thank you, Mark. It's great to be here.
Host: So, let's start with the big question. Is social media actually bad for teenagers?
Dr. Jenkins: Well, it's not black and white. Social media allows young people to connect, find communities, and express themselves. However, the data shows a worrying correlation between heavy use and anxiety or depression.
Host: What specifically causes this anxiety?
Dr. Jenkins: A major factor is comparison. Teens see curated, "perfect" versions of their friends' lives and feel inadequate. They think, "Why isn't my life that exciting?". This is often called FOMO, or Fear Of Missing Out.
Host: I see. And what about sleep? My teenage son stays up late scrolling.
Dr. Jenkins: Exactly. Sleep disruption is huge. The blue light from screens affects melatonin, and the constant notifications keep the brain alert. A tired teen is more likely to be irritable and anxious.
Host: What about cyberbullying?
Dr. Jenkins: Unfortunately, it's very common. Unlike playground bullying, cyberbullying follows you home. It's 24/7.
Host: That sounds terrifying. So, what can parents do? Ban phones?
Dr. Jenkins: Banning often backfires. It isolates them from their peers. Instead, encourage "tech-free zones", like the dinner table. And importantly, model good behavior yourself. If you are always on your phone, they will be too.
Host: Great advice. Thank you, Dr. Jenkins.`;

const textLondon = `LONDON: A CITY OF CONTRASTS\n\nLondon is one of the most exciting and diverse cities in the world. It is a place where history and modernity stand side by side. You can see the ancient Tower of London, which is nearly 1,000 years old, and just across the river, the Shard, a futuristic glass skyscraper that dominates the skyline.\n\nThe city is famous for its green spaces. Despite being a huge metropolis, London has eight Royal Parks, including Hyde Park and Regent's Park. These parks are essential for the city's residents, offering a quiet escape from the noise and traffic of urban life. On sunny days, office workers often eat their lunch on the grass, and tourists rent boats on the Serpentine lake.\n\nHowever, London also faces challenges. The cost of living is very high, making it difficult for young people to afford rent. Transport can also be a problem. The "Tube" (the underground system) is extensive but can be overcrowded and hot in the summer. Millions of commuters use it every day to get to work.\n\nCulturally, London is a melting pot. More than 300 languages are spoken in the city, and you can find food from every corner of the globe. From the curry houses of Brick Lane to the street food markets in Camden, the culinary variety reflects the city's multicultural population.`;

export const ingleseQuestions: Question[] = [
  // --- READING COMPREHENSION ---
  { id: 'eng-10-reading-01', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - B1/B2', contextText: textBluePlanet, text: "What is the main purpose of Paragraph A?", options: [ "To explain the history of Agenda 2030.", "To list professional careers in ecology.", "To provide examples of how individuals can help the planet.", "To describe the differences between baths and showers." ], correctAnswerIndex: 2, explanation: "Il paragrafo A si concentra su azioni pratiche quotidiane ('everyday actions') come fare la doccia veloce o gestire i rifiuti per ridurre l'impronta ecologica." },
  { id: 'eng-10-reading-02', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - B1/B2', contextText: textBluePlanet, text: "According to the text, Blue Planet 2 is...", options: [ "a short movie about marine life.", "a documentary that took a long time to produce.", "a series narrated by a group of university students.", "a program only about coral reefs." ], correctAnswerIndex: 1, explanation: "Il testo specifica che la produzione è stata un 'massive effort' che ha richiesto 'four years of work'." },
  { id: 'eng-10-reading-03', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - B1/B2', contextText: textBluePlanet, text: "What does the example of the 'giant trevally' prove?", options: [ "That some fish have unusual hunting behaviors.", "That birds are the main enemy of fish.", "That fish are not very smart.", "That coral reefs are dangerous for birds." ], correctAnswerIndex: 0, explanation: "Viene descritto come un pesce che salta fuori dall'acqua per catturare uccelli, un comportamento di caccia insolito e sorprendente che dimostra intelligenza." },
  { id: 'eng-10-reading-04', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - B1/B2', contextText: textBluePlanet, text: "What is the main 'warning' mentioned in Paragraph D?", options: [ "The disappearance of dolphins.", "The lack of awareness in schools.", "The danger of plastic in the oceans.", "The beauty of the underwater world." ], correctAnswerIndex: 2, explanation: "Il testo definisce l'inquinamento da plastica ('plastic pollution') come un 'terrible magic' e un drammatico avvertimento ('warning')." },
  { id: 'eng-10-reading-05', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - B1/B2', contextText: textBluePlanet, text: "What is a specific problem related to biomass energy mentioned in the text?", options: [ "It is impossible to use in some countries.", "It is too expensive for most citizens.", "It produces a small amount of air pollution when burned.", "It cannot be made from wood or plants." ], correctAnswerIndex: 2, explanation: "Si menziona esplicitamente che bruciare biomasse può creare 'a little smoke', il che rappresenta un piccolo svantaggio ambientale." },
  { id: 'eng-10-reading-06', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Short Answer Adaptation', contextText: textBluePlanet, text: "According to Paragraph A, what is a practical way to avoid wasting water?", options: [ "Taking a long bath", "Choosing a quick shower", "Drinking less water", "Watering plants at night" ], correctAnswerIndex: 1, explanation: "Il testo suggerisce: 'choosing a quick shower is a practical way to avoid wasting water'." },
  { id: 'eng-10-reading-07', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Short Answer Adaptation', contextText: textBluePlanet, text: "Who is the narrator of the series Blue Planet 2?", options: [ "Sir David Attenborough", "The Queen of England", "A famous actor", "An unknown scientist" ], correctAnswerIndex: 0, explanation: "Il testo afferma: 'Narrated by the legendary Sir David Attenborough'." },
  { id: 'eng-10-reading-08', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Short Answer Adaptation', contextText: textBluePlanet, text: "How many hours of underwater filming were involved in the production?", options: [ "4,000 hours", "6,000 hours", "10,000 hours", "2,000 hours" ], correctAnswerIndex: 1, explanation: "Il testo cita '6,000 hours of underwater filming'." },
  { id: 'eng-10-reading-09', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Short Answer Adaptation', contextText: textBluePlanet, text: "What do tuskfish use to hit molluscs against coral reefs?", options: [ "Their tails", "Their fins", "Their mouth", "Their heads" ], correctAnswerIndex: 2, explanation: "Il tuskfish 'uses its mouth to hit molluscs against coral reefs'." },
  { id: 'eng-10-reading-10', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Short Answer Adaptation', contextText: textBluePlanet, text: "Where does geothermal energy come from?", options: [ "From the wind", "From the sun", "From inside the ground", "From ocean waves" ], correctAnswerIndex: 2, explanation: "Il testo spiega che l'energia geotermica 'comes from the heat inside the ground'." },
  { id: 'eng-10-reading-11', type: QuestionType.MATRIX, topic: 'Reading - Matching Titles', contextText: textBluePlanet, text: "Match the paragraphs (A-F) with the correct titles.", matrixRows: ["Paragraph A", "Paragraph B", "Paragraph C", "Paragraph D", "Paragraph E", "Paragraph F"], matrixCols: [ "Individual Actions for Sustainability", "A Professional Documentary Production", "Marine Intelligence and Behavior", "A Major Threat to the Sea", "Clean Alternatives for the Future", "A Call for Global Responsibility" ], matrixCorrectAnswer: [0, 1, 2, 3, 4, 5], explanation: "A: Azioni individuali. B: Documentario BBC. C: Intelligenza pesci. D: Minaccia plastica. E: Energie rinnovabili. F: Responsabilità globale." },

  // --- LISTENING COMPREHENSION ---
  { id: 'eng-10-listening-01', type: QuestionType.MULTIPLE_CHOICE, topic: 'Listening - Comprehension', contextText: "Transcript available via audio.", audioScript: scriptTeenMentalHealth, text: "What is the main topic of the interview?", options: [ "The benefits of physical exercise for teens.", "The impact of social media on teenage mental health.", "How to become a successful influencer.", "The history of the internet." ], correctAnswerIndex: 1, explanation: "L'host introduce l'argomento dicendo: 'the impact of social media on teenage mental health'." },
  { id: 'eng-10-listening-02', type: QuestionType.MULTIPLE_CHOICE, topic: 'Listening - Detail', audioScript: scriptTeenMentalHealth, text: "According to Dr. Jenkins, social media is...", options: [ "completely bad for everyone.", "not strictly black and white (it has pros and cons).", "only good for finding communities.", "a waste of time." ], correctAnswerIndex: 1, explanation: "La dottoressa afferma: 'it's not black and white', indicando che ci sono aspetti positivi (connessione) e negativi." },
  { id: 'eng-10-listening-03', type: QuestionType.MULTIPLE_CHOICE, topic: 'Listening - Detail', audioScript: scriptTeenMentalHealth, text: "What causes anxiety in teenagers according to the interview?", options: [ "Comparison with 'perfect' lives of others.", "Having too many followers.", "Posting too many photos.", "Not having a phone." ], correctAnswerIndex: 0, explanation: "Dr. Jenkins dice: 'A major factor is comparison. Teens see curated, perfect versions of their friends' lives'." },
  { id: 'eng-10-listening-04', type: QuestionType.MULTIPLE_CHOICE, topic: 'Listening - Vocabulary', audioScript: scriptTeenMentalHealth, text: "What does the acronym FOMO stand for?", options: [ "Fear Of Missing Out", "Feeling Of Moving On", "Fast Online Media Outlet", "Friends On Mobile Only" ], correctAnswerIndex: 0, explanation: "Viene definito esplicitamente nel dialogo: 'FOMO, or Fear Of Missing Out'." },
  { id: 'eng-10-listening-05', type: QuestionType.MULTIPLE_CHOICE, topic: 'Listening - Detail', audioScript: scriptTeenMentalHealth, text: "How does blue light affect teenagers?", options: [ "It makes them hungry.", "It improves their vision.", "It affects melatonin and disrupts sleep.", "It helps them wake up early." ], correctAnswerIndex: 2, explanation: "Dr. Jenkins spiega: 'The blue light from screens affects melatonin... and keeps the brain alert'." },
  { id: 'eng-10-listening-06', type: QuestionType.MULTIPLE_CHOICE, topic: 'Listening - Detail', audioScript: scriptTeenMentalHealth, text: "What is the main difference between cyberbullying and playground bullying?", options: [ "Cyberbullying is less dangerous.", "Playground bullying happens at night.", "Cyberbullying follows you home (24/7).", "There is no difference." ], correctAnswerIndex: 2, explanation: "Dr. Jenkins nota che 'cyberbullying follows you home. It's 24/7', a differenza del bullismo scolastico." },
  { id: 'eng-10-listening-07', type: QuestionType.MULTIPLE_CHOICE, topic: 'Listening - Inference', audioScript: scriptTeenMentalHealth, text: "Why does Dr. Jenkins suggest NOT banning phones completely?", options: [ "Because phones are expensive.", "Because it isolates teens from their peers.", "Because parents need to call them.", "Because teens will buy new ones." ], correctAnswerIndex: 1, explanation: "Dice che vietarli 'often backfires. It isolates them from their peers'." },
  { id: 'eng-10-listening-08', type: QuestionType.MULTIPLE_CHOICE, topic: 'Listening - Advice', audioScript: scriptTeenMentalHealth, text: "What advice does Dr. Jenkins give to parents?", options: [ "Check their messages every hour.", "Model good behavior (e.g. not using phones all the time).", "Buy them a better phone.", "Stop using social media yourself forever." ], correctAnswerIndex: 1, explanation: "Il consiglio finale è: 'model good behavior yourself. If you are always on your phone, they will be too'." },

  // --- GRAMMAR ---
  { id: 'eng-10-grammar-01', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Zero Conditional', text: "Choose the correct form to complete the Zero Conditional sentence: 'If you mix blue and yellow, you _______ (get) green.'", options: ["get", "will get", "would get", "got"], correctAnswerIndex: 0, explanation: "Lo Zero Conditional (verità universali) richiede il Present Simple sia nella if-clause che nella principale." },
  { id: 'eng-10-grammar-02', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - First Conditional', text: "Transform into First Conditional: 'If it rains tomorrow, I _______ (not / go) to the beach.'", options: ["don't go", "won't go", "wouldn't go", "didn't go"], correctAnswerIndex: 1, explanation: "Il First Conditional (eventi futuri possibili) usa 'will' + verbo base nella frase principale." },
  { id: 'eng-10-grammar-03', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Correlative Conjunctions', text: "Which is the correct translation for 'Sia Anna che Marco sono qui'?", options: ["Neither Anna nor Marco is here.", "Both Anna and Marco is here.", "Both Anna and Marco are here.", "Either Anna or Marco are here."], correctAnswerIndex: 2, explanation: "Con 'Both...and', il verbo è sempre plurale ('are')." },
  { id: 'eng-10-grammar-04', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Subject-Verb Agreement', text: "Choose the correct form: 'Neither the buses nor the underground _______ (be) working today.'", options: ["is", "are", "were", "have"], correctAnswerIndex: 0, explanation: "Con 'neither...nor', il verbo concorda con il soggetto più vicino ('the underground', singolare -> 'is')." },
  { id: 'eng-10-grammar-05', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Genitive', text: "What is the meaning of 'A friend of Michela's' compared to 'Michela's friend'?", options: [ "It implies Michela has many friends, and this is one of them.", "It means Michela has only one friend.", "It is grammatically incorrect.", "It implies the friend is a relative." ], correctAnswerIndex: 0, explanation: "Il doppio genitivo ('A friend of Michela's') suggerisce che sia 'uno dei tanti' amici." },
  { id: 'eng-10-grammar-06', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Adverbs', text: "Which is the correct adverb form of the adjective 'Happy'?", options: ["Happyly", "Happily", "Happy", "Happiely"], correctAnswerIndex: 1, explanation: "Gli aggettivi che terminano in -y cambiano la y in i prima di aggiungere -ly (Happy -> Happily)." },
  { id: 'eng-10-grammar-07', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Word Order', text: "Which sentence is correct?", options: ["He drives carefully it.", "He drives it carefully.", "He carefully drives it.", "He carefully it drives."], correctAnswerIndex: 1, explanation: "L'avverbio non deve separare il verbo dal complemento oggetto se questo è un pronome. 'He drives it carefully' è l'ordine corretto." },
  { id: 'eng-10-grammar-08', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Infinitive of Purpose', text: "Complete the sentence: 'I go to the gym _______ (get) stronger.'", options: ["for get", "to get", "for getting", "getting"], correctAnswerIndex: 1, explanation: "Per esprimere lo scopo si usa l'infinito con to ('to get')." },
  { id: 'eng-10-grammar-09', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Passive Voice', text: "Transform into Passive: 'My company makes these gadgets.'", options: ["These gadgets make my company.", "These gadgets are made by my company.", "These gadgets were made by my company.", "My company is made by these gadgets."], correctAnswerIndex: 1, explanation: "Present Passive: Oggetto diventa soggetto + am/is/are + Past Participle ('are made')." },
  { id: 'eng-10-grammar-10', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Verb Patterns', text: "Complete the sentence: 'I'm looking forward to _______ (meet) you.'", options: ["meet", "to meet", "meeting", "met"], correctAnswerIndex: 2, explanation: "Dopo 'look forward to', il 'to' è una preposizione, quindi segue il gerundio (-ing)." },
  { id: 'eng-10-grammar-11', type: QuestionType.MULTIPLE_CHOICE, topic: 'Grammar - Phrasal Verbs', text: "Complete the sentence: 'The plane _______ at 9:00 AM.'", options: ["took off", "took up", "took out", "took in"], correctAnswerIndex: 0, explanation: "'Take off' è il phrasal verb corretto per indicare il decollo di un aereo." },

  // --- NEW READING: LONDON ---
  { id: 'eng-10-reading-new-01', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Detail', contextText: textLondon, text: "Why are Royal Parks considered essential for London's residents?", options: [ "Because they are good for farming.", "They offer a quiet escape from noise and traffic.", "They are the only places to eat lunch.", "They contain many historic castles." ], correctAnswerIndex: 1, explanation: "Il testo dice che i parchi offrono 'a quiet escape from the noise and traffic of urban life'." },
  { id: 'eng-10-reading-new-02', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Detail', contextText: textLondon, text: "What architectural contrast is mentioned in the first paragraph?", options: [ "Between the river and the parks.", "Between the ancient Tower of London and the modern Shard.", "Between the Tube and the buses.", "Between Brick Lane and Camden." ], correctAnswerIndex: 1, explanation: "Il testo contrappone la 'ancient Tower of London' al 'futuristic glass skyscraper' (The Shard)." },
  { id: 'eng-10-reading-new-03', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Vocabulary', contextText: textLondon, text: "In the context of the text, what does the word 'commuters' mean?", options: [ "People who travel to work every day.", "Tourists visiting the city.", "People who live in parks.", "Drivers of black cabs." ], correctAnswerIndex: 0, explanation: "'Commuters' si riferisce ai milioni di persone che 'use it [the Tube] every day to get to work'." },
  { id: 'eng-10-reading-new-04', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Inference', contextText: textLondon, text: "What is implied about London's food scene?", options: [ "It is very expensive and only for rich people.", "It is limited to traditional British food.", "It is diverse due to the multicultural population.", "It is mostly fast food." ], correctAnswerIndex: 2, explanation: "Il testo afferma che la varietà culinaria 'reflects the city's multicultural population', citando cibo da ogni angolo del globo." },
  { id: 'eng-10-reading-new-05', type: QuestionType.MULTIPLE_CHOICE, topic: 'Reading - Detail', contextText: textLondon, text: "What is a negative aspect of the 'Tube' mentioned in the text?", options: [ "It is too slow.", "It does not go to the city center.", "It can be overcrowded and hot in summer.", "It is too expensive for tourists." ], correctAnswerIndex: 2, explanation: "Il testo specifica che la metropolitana 'can be overcrowded and hot in the summer'." }
];