import { Question, QuestionType } from '../types';

export const matematicaQuestions: Question[] = [
  // TEST 1: DISEQUAZIONI
  {
    id: 'mat-10-real-01',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Algebra - Disequazioni Lineari',
    contextText: "Un centro di mediazione familiare offre due piani tariffari per le sessioni di consulenza.\n- Piano A: quota di iscrizione annuale di 150€ e costo di 40€ per ogni seduta.\n- Piano B: nessuna quota di iscrizione, costo di 65€ per ogni seduta.",
    text: "Quante sedute (x) deve effettuare una famiglia in un anno affinché il Piano A risulti economicamente più conveniente del Piano B?",
    options: ["Meno di 6 sedute (x < 6)", "Almeno 7 sedute (x > 6)", "Esattamente 6 sedute", "Almeno 10 sedute (x > 9)"],
    correctAnswerIndex: 1,
    explanation: "La condizione di convenienza è CostoA < CostoB. Impostiamo la disequazione: 150 + 40x < 65x. Risolvendo: 150 < 25x -> 6 < x. Quindi x deve essere maggiore di 6, cioè almeno 7 sedute.",
  },
  // TEST 2: EQUAZIONI
  {
    id: 'mat-10-real-02',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Algebra - Equazioni di Primo Grado',
    contextText: "In un test psico-attitudinale composto da 50 domande:\n- Ogni risposta corretta vale +4 punti.\n- Ogni risposta errata toglie 1 punto (-1).\n- Ogni risposta non data vale 0 punti.\nUno studente ha risposto a TUTTE le domande ottenendo un punteggio finale di 145 punti.",
    text: "Quante risposte corrette ha fornito lo studente?",
    options: ["35", "40", "39", "29"],
    correctAnswerIndex: 2,
    explanation: "Sia x le risposte corrette. Quelle errate sono (50-x). L'equazione è: 4x - 1(50 - x) = 145. Risolvendo: 4x - 50 + x = 145 -> 5x = 195 -> x = 39.",
  },
  // TEST 3: SISTEMI DI DISEQUAZIONI
  {
    id: 'mat-10-real-03',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Algebra - Sistemi di Disequazioni',
    contextText: "Un educatore ha un budget di 500€ per acquistare materiale ludico.\n- Scatole costruzioni (x): 25€ l'una.\n- Kit pittura (y): 15€ l'uno.\nVincoli:\n1. Deve acquistare almeno 10 kit di pittura.\n2. Per motivi di spazio, il numero totale di oggetti (x + y) non deve superare 25.",
    text: "Quale dei seguenti sistemi di disequazioni rappresenta correttamente tutti i vincoli del problema?",
    options: ["25x + 15y ≥ 500;\n y ≤ 10;\n x + y ≥ 25", "25x + 15y ≤ 500;\n x ≥ 10;\n x + y < 25", "25x + 15y ≤ 500;\n y ≥ 10;\n x + y ≤ 25", "15x + 25y ≤ 500;\n y > 10;\n x + y ≤ 25"],
    correctAnswerIndex: 2,
    explanation: "Il primo vincolo è il budget (prezzo*quantità ≤ 500). Il secondo è pedagogico (y ≥ 10). Il terzo è spaziale (x + y ≤ 25). L'opzione C include correttamente tutti i segni di disuguaglianza.",
  },
  // TEST 7: RETTE PARALLELE
  {
    id: 'mat-10-real-07',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Geometria Analitica - Rette Parallele',
    text: "Una strada rettilinea segue l'equazione y = 3x + 2. Il comune vuole costruire un viale pedonale PARALLELO alla strada che passi davanti a un liceo situato nel punto P(2, -1). Qual è l'equazione del viale pedonale?",
    options: ["y = 3x + 5", "y = -3x - 1", "y = 1/3x - 7", "y = 3x - 7"],
    correctAnswerIndex: 3,
    explanation: "Rette parallele hanno lo stesso coefficiente angolare m. Qui m=3. Usiamo la formula della retta per un punto: y - yP = m(x - xP). Sostituendo: y - (-1) = 3(x - 2) -> y + 1 = 3x - 6 -> y = 3x - 7.",
  },
  // TEST 8: RETTE PERPENDICOLARI
  {
    id: 'mat-10-real-08',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Geometria Analitica - Rette Perpendicolari',
    text: "Un viale principale ha equazione y = -1/2x + 4. Si vuole costruire una traversa PERPENDICOLARE al viale che passi per l'ingresso di un ospedale situato nel punto H(3, 2). Qual è l'equazione della traversa?",
    options: ["y = -2x + 8", "y = 2x - 4", "y = 1/2x + 2", "y = 2x + 4"],
    correctAnswerIndex: 1,
    explanation: "Il coefficiente del viale è m = -1/2. La perpendicolare deve avere m' antireciproco: m' = -1/m = 2. Retta per H(3,2) con m'=2: y - 2 = 2(x - 3) -> y = 2x - 6 + 2 -> y = 2x - 4.",
  },
  // TEST 6: DISTANZA
  {
    id: 'mat-10-real-06',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Geometria Analitica - Distanza tra Punti',
    text: "Su una mappa (unità = 100m), un centro giovanile è in A(-3, 2) e la biblioteca in B(5, 8). Quanto distano in linea d'aria i due edifici nella realtà?",
    options: ["800 metri", "1400 metri", "1000 metri", "100 metri"],
    correctAnswerIndex: 2,
    explanation: "Applichiamo la formula della distanza: √[(5 - (-3))² + (8 - 2)²] = √[8² + 6²] = √[64 + 36] = √100 = 10 unità grafiche. Poiché 1 unità = 100m, la distanza reale è 10 * 100 = 1000 metri.",
  },
  // TEST 11: MODELLIZZAZIONE
  {
    id: 'mat-10-real-11',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Relazioni e Funzioni - Modellizzazione',
    contextText: "Due città hanno andamenti demografici opposti:\n- Città A: parte da 50.000 abitanti e cresce di 1.000 l'anno.\n- Città B: parte da 65.000 abitanti e diminuisce di 500 l'anno.",
    text: "Tra quanti anni la popolazione della città A supererà quella della città B (punto di sorpasso)?",
    options: ["Dopo 8 anni", "Dopo 10 anni", "Dopo 15 anni", "Mai, le rette sono parallele"],
    correctAnswerIndex: 1,
    explanation: "Modelli: PopA = 50000 + 1000t; PopB = 65000 - 500t. Sorpasso quando PopA > PopB: 1000t + 500t > 65000 - 50000 -> 1500t > 15000 -> t > 10.",
  },
  // TEST 4: SOGLIA POVERTA
  {
    id: 'mat-10-real-04',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Algebra - Disequazioni e Realtà',
    contextText: "Una famiglia è considerata 'non a rischio' se il reddito mensile R soddisfa: R ≥ 1,2 * P, dove P è la soglia di povertà (800€).\nUna famiglia ha un reddito fisso di 650€ più un sussidio 'x' per ognuno dei suoi 3 figli.",
    text: "Qual è l'importo minimo del sussidio x (per figlio) affinché la famiglia non sia a rischio?",
    options: ["Circa 80€", "Esattamente 50€", "Almeno 150€", "Circa 104€"],
    correctAnswerIndex: 3,
    explanation: "Soglia critica: 1,2 * 800 = 960€. Reddito famiglia: 650 + 3x. Disequazione: 650 + 3x ≥ 960 -> 3x ≥ 310 -> x ≥ 103,33. L'importo minimo intero più vicino è circa 104€.",
  },
  // TEST 13: RETTA 2 PUNTI
  {
    id: 'mat-10-real-13',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Geometria Analitica - Rette per due punti',
    contextText: "Durante uno scavo archeologico vengono trovati due frammenti di un muro rettilineo nei punti A(1, 3) e B(4, 9).",
    text: "Qual è l'equazione della retta che rappresenta l'antico muro?",
    options: ["y = 3x", "y = 2x + 1", "y = 2x + 3", "y = 0.5x + 2.5"],
    correctAnswerIndex: 1,
    explanation: "Calcoliamo il coefficiente angolare m = (y2-y1)/(x2-x1) = (9-3)/(4-1) = 6/3 = 2. Usiamo la retta per A: y - 3 = 2(x - 1) -> y = 2x - 2 + 3 -> y = 2x + 1.",
  },
  // TEST 12: PROFITTO
  {
    id: 'mat-10-real-12',
    type: QuestionType.MULTIPLE_CHOICE,
    topic: 'Relazioni e Funzioni - Profitto',
    contextText: "Una cooperativa produce marmellate.\n- Costi fissi giornalieri: 200€\n- Costo produzione per barattolo: 1,50€\n- Prezzo vendita per barattolo: 4,00€",
    text: "Quanti barattoli (x) bisogna vendere al giorno per avere un profitto di almeno 100€?",
    options: ["Almeno 80 barattoli", "Almeno 200 barattoli", "Almeno 120 barattoli", "Almeno 40 barattoli"],
    correctAnswerIndex: 2,
    explanation: "Profitto = Ricavi - Costi. Ricavi = 4x. Costi = 1,5x + 200. Vogliamo Profitto ≥ 100. Quindi: 4x - (1,5x + 200) ≥ 100 -> 2,5x - 200 ≥ 100 -> 2,5x ≥ 300 -> x ≥ 120.",
  },
  // Q1-Q15 GPT/Sim
  { id: 'mat-10-gpt-01', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Una guida museale costa 4 € di prenotazione fissa più 2 € per ogni studente partecipante. In totale la classe paga 18 €. Quanti studenti hanno partecipato?", options: ["5", "8", "7", "9"], correctAnswerIndex: 2, explanation: "Se n è il numero di studenti, l'equazione è 4 + 2n = 18. Sottraendo il costo fisso: 2n = 14, da cui n = 7." },
  { id: 'mat-10-gpt-02', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Per un laboratorio scolastico si noleggia una sala: si paga una quota fissa di 21 € più 7 € per ogni partecipante. Il totale è 175 €. Quanti sono i partecipanti?", options: ["22", "25", "24", "28"], correctAnswerIndex: 0, explanation: "Impostiamo l'equazione 21 + 7n = 175. Sottraendo la quota fissa: 7n = 154. Dividendo per 7: n = 22." },
  { id: 'mat-10-gpt-03', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Un recinto rettangolare ha area 96 m². Il lato lungo è 4 m più del lato corto. Quanto misura il lato corto?", options: ["12 m", "10 m", "5 m", "8 m"], correctAnswerIndex: 3, explanation: "Sia x il lato corto. Il lato lungo è x + 4. Area: x(x + 4) = 96 → x² + 4x - 96 = 0. Risolvendo (o provando le opzioni): 8(8+4) = 8*12 = 96." },
  { id: 'mat-10-gpt-04', type: QuestionType.MULTIPLE_CHOICE, topic: 'Numeri', text: "Un laboratorio compra kit didattici: ogni kit costa 8 € e c’è una spesa di spedizione fissa di 6 €. Il budget totale è 50 €. Qual è il numero massimo di kit acquistabili?", options: ["4", "5", "6", "7"], correctAnswerIndex: 1, explanation: "Disequazione: 8k + 6 ≤ 50 → 8k ≤ 44 → k ≤ 5,5. Il numero massimo intero è 5." },
  { id: 'mat-10-gpt-05', type: QuestionType.MULTIPLE_CHOICE, topic: 'Numeri', text: "Un dispositivo deve essere tarato a 100 con tolleranza ±3. Quale condizione descrive correttamente i valori accettabili di x?", options: ["97 < x < 103", "x ≤ 97 oppure x ≥ 103", "97 ≤ x ≤ 103", "100 ≤ x ≤ 103"], correctAnswerIndex: 2, explanation: "La tolleranza ±3 significa che il valore può scostarsi di al massimo 3 unità da 100: |x - 100| ≤ 3, ovvero 97 ≤ x ≤ 103." },
  { id: 'mat-10-gpt-06', type: QuestionType.MULTIPLE_CHOICE, topic: 'Numeri', text: "Risolvi il sistema:\n2x - 5 ≥ 1\nx + 3 < 7", options: ["3 ≤ x < 4", "x < 4", "x ≥ 3", "x ≥ 4"], correctAnswerIndex: 0, explanation: "Prima disequazione: 2x ≥ 6 → x ≥ 3. Seconda: x < 4. Intersezione: 3 ≤ x < 4." },
  { id: 'mat-10-gpt-07', type: QuestionType.MULTIPLE_CHOICE, topic: 'Numeri', text: "Per una festa si comprano casse da 6 bottiglie. Il totale di bottiglie deve essere almeno 48 e al massimo 66. Se x è il numero di casse, quali sono i possibili valori interi di x?", options: ["{7, 8, 9, 10, 11}", "{8, 9, 10, 11, 12}", "{9, 10, 11, 12}", "{8, 9, 10, 11}"], correctAnswerIndex: 3, explanation: "48 ≤ 6x ≤ 66. Dividendo per 6: 8 ≤ x ≤ 11. I valori interi sono {8, 9, 10, 11}." },
  { id: 'mat-10-gpt-08', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Quale punto appartiene alla retta 2x + 3y = 5?", options: ["(2, 1)", "(1, 1)", "(1, 2)", "(0, 2)"], correctAnswerIndex: 1, explanation: "Sostituendo (1, 1): 2(1) + 3(1) = 2 + 3 = 5. L'uguaglianza è vera." },
  { id: 'mat-10-gpt-09', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Due piani dati mobile hanno costo mensile (in euro) in funzione dei GB (g).\nPiano A: C = 5 + 2g\nPiano B: C = 11 + g\nPer quale coppia (g, C) i due piani hanno lo stesso costo?", options: ["(17, 6)", "(5, 11)", "(6, 17)", "(6, 11)"], correctAnswerIndex: 2, explanation: "Uguagliamo i costi: 5 + 2g = 11 + g → g = 6. Calcoliamo C: C = 5 + 2(6) = 17. Punto (6, 17)." },
  { id: 'mat-10-gpt-10', type: QuestionType.MULTIPLE_CHOICE, topic: 'Spazio e figure', text: "La retta r ha equazione y = 2x - 3. Qual è l’equazione della retta s, parallela a r, che passa per il punto P(1, 4)?", options: ["y = 2x + 3", "y = 2x - 1", "y = -1/2x + 9/2", "y = 2x + 2"], correctAnswerIndex: 3, explanation: "La parallela ha la stessa pendenza m = 2. Equazione: y = 2x + q. Sostituisco P(1, 4): 4 = 2(1) + q → q = 2. Quindi y = 2x + 2." },
  { id: 'mat-10-gpt-11', type: QuestionType.MULTIPLE_CHOICE, topic: 'Spazio e figure', text: "La retta t ha equazione 4x - 2y + 6 = 0. Quale tra le seguenti rette è perpendicolare a t?", options: ["y = -2x + 1", "y = -1/2x + 1", "y = 1/2x + 1", "y = -x + 1"], correctAnswerIndex: 1, explanation: "Pendenza di t: -2y = -4x - 6 → y = 2x + 3 (m = 2). La perpendicolare ha m' = -1/2. L'opzione con m = -1/2 è quella corretta." },
  { id: 'mat-10-gpt-12', type: QuestionType.MULTIPLE_CHOICE, topic: 'Spazio e figure', text: "La retta r ha equazione 3x + y - 6 = 0. Trova l’equazione della retta perpendicolare a r e passante per A(3, -2).", options: ["y = 1/3x - 3", "y = -3x + 7", "y = 3x - 11", "y = -1/3x - 1"], correctAnswerIndex: 0, explanation: "r: y = -3x + 6 (m = -3). Perpendicolare m' = 1/3. Retta: y - (-2) = 1/3(x - 3) → y + 2 = 1/3x - 1 → y = 1/3x - 3." },
  { id: 'mat-10-gpt-13', type: QuestionType.MULTIPLE_CHOICE, topic: 'Spazio e figure', text: "Due punti di una pista ciclabile sono A(2, 1) e B(8, 4). Qual è l’equazione della retta che passa per A e B?", options: ["y = 2x", "y = 1/2x + 1", "y = 1/2x", "y = -1/2x"], correctAnswerIndex: 2, explanation: "m = (4 - 1)/(8 - 2) = 3/6 = 1/2. Retta per A: y - 1 = 1/2(x - 2) → y - 1 = 1/2x - 1 → y = 1/2x." },
  { id: 'mat-10-gpt-14', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Un’associazione prepara pacchi: x = grandi (costo 2), y = piccoli (costo 1). Vincoli:\n1) 2x + y ≤ 10 (budget)\n2) y ≥ x + 1 (almeno 1 piccolo in più dei grandi)\n3) x, y ≥ 0\nQuale coppia (x, y) rispetta tutti i vincoli?", options: ["(1, 1)", "(4, 3)", "(2, 0)", "(3, 4)"], correctAnswerIndex: 3, explanation: "Testiamo (3, 4): 2(3)+4=10≤10 (ok), 4≥3+1 (ok). Gli altri falliscono uno o più vincoli." },
  { id: 'mat-10-gpt-15', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Il costo per stampare volantini è C = 0,15x + 3 (x = numero volantini). Budget massimo 30 €. Qual è il numero massimo di volantini stampabili?", options: ["179", "180", "181", "200"], correctAnswerIndex: 1, explanation: "0,15x + 3 ≤ 30 → 0,15x ≤ 27 → x ≤ 27 / 0,15 = 180." },
  { id: 'mat-10-sim-01', type: QuestionType.MULTIPLE_CHOICE, topic: 'Algebra', text: "Un’associazione culturale organizza un evento. Il costo totale C è composto da una quota fissa di 150 euro per l’affitto della sala e 5 euro per ogni partecipante n. Quale delle seguenti espressioni rappresenta correttamente il costo medio per partecipante?", options: ["150 + 5n", "(150 + 5n) / n", "155n", "(150n + 5) / n"], correctAnswerIndex: 1, explanation: "Il costo totale è 150 + 5n. Il costo medio si ottiene dividendo il costo totale per il numero di partecipanti n: (150 + 5n) / n." },
  { id: 'mat-10-sim-02', type: QuestionType.MULTIPLE_CHOICE, topic: 'Geometria Analitica', text: "Due rette nel piano cartesiano hanno equazioni y = 3x - 4 e y = -1/3x + 2. In che tipo di relazione geometrica si trovano?", options: ["Sono parallele", "Sono perpendicolari", "Sono coincidenti", "Si intersecano nell'origine"], correctAnswerIndex: 1, explanation: "I coefficienti angolari sono m1 = 3 e m2 = -1/3. Poiché il loro prodotto è -1, le rette sono perpendicolari." },
  { id: 'mat-10-sim-03', type: QuestionType.MULTIPLE_CHOICE, topic: 'Algebra', text: "In un test di 20 domande, ogni risposta corretta vale 5 punti e ogni risposta errata toglie 2 punti. Se uno studente risponde a tutte le domande e ottiene 72 punti, quante risposte corrette (x) ha dato?", options: ["16", "14", "12", "18"], correctAnswerIndex: 0, explanation: "Sia x il numero di risposte corrette. Le errate sono (20-x). Equazione: 5x - 2(20-x) = 72 => 5x - 40 + 2x = 72 => 7x = 112 => x = 16." },
  { id: 'mat-10-sim-04', type: QuestionType.MULTIPLE_CHOICE, topic: 'Algebra', text: "Data la disequazione (x - 3) / 2 > x + 1, quali sono le sue soluzioni?", options: ["x > -5", "x < -5", "x > 5", "x < -1"], correctAnswerIndex: 1, explanation: "Moltiplico per 2: x - 3 > 2x + 2 => -x > 5 => x < -5." },
  { id: 'mat-10-sim-05', type: QuestionType.MULTIPLE_CHOICE, topic: 'Geometria Analitica', text: "Un punto P si trova sulla retta di equazione y = 2x + 5 e ha ascissa x = -3. Qual è la sua ordinata?", options: ["-1", "11", "5", "-11"], correctAnswerIndex: 0, explanation: "Sostituisco x = -3 nell'equazione: y = 2(-3) + 5 = -6 + 5 = -1." },
  { id: 'mat-10-sim-06', type: QuestionType.MULTIPLE_CHOICE, topic: 'Geometria Analitica', text: "Quale tra i seguenti sistemi di disequazioni descrive i punti che si trovano nel secondo quadrante del piano cartesiano?", options: ["x > 0, y > 0", "x < 0, y > 0", "x < 0, y < 0", "x > 0, y < 0"], correctAnswerIndex: 1, explanation: "Il secondo quadrante è caratterizzato da ascisse negative (x < 0) e ordinate positive (y > 0)." },
  { id: 'mat-10-sim-07', type: QuestionType.MULTIPLE_CHOICE, topic: 'Geometria Analitica', text: "Sia r la retta di equazione y = 4. Quale delle seguenti rette è perpendicolare ad essa?", options: ["x = 2", "y = -4", "y = 4x", "x = y"], correctAnswerIndex: 0, explanation: "La retta y = 4 è orizzontale. Una retta perpendicolare deve essere verticale, quindi del tipo x = k. Tra le opzioni, x = 2 è l'unica retta verticale." },
  { id: 'mat-10-sim-08', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e Funzioni', text: "Una società di noleggio auto offre due tariffe:\n- Tariffa A: 40€ fissi + 0,20€ al km.\n- Tariffa B: 20€ fissi + 0,40€ al km.\nPer quale numero di chilometri k le due tariffe sono uguali?", options: ["50 km", "200 km", "100 km", "150 km"], correctAnswerIndex: 2, explanation: "Uguagliamo i costi: 40 + 0.20k = 20 + 0.40k => 20 = 0.20k => k = 100." },
  { id: 'mat-10-sim-09', type: QuestionType.MULTIPLE_CHOICE, topic: 'Geometria Analitica', text: "La retta passante per il punto A(0, 3) e parallela all’asse delle ascisse ha equazione:", options: ["x = 3", "y = 3", "y = x + 3", "x = 0"], correctAnswerIndex: 1, explanation: "Le rette parallele all'asse x sono del tipo y = k. Passando per A(0, 3), l'equazione è y = 3." },
  { id: 'mat-10-sim-10', type: QuestionType.MULTIPLE_CHOICE, topic: 'Algebra', text: "Quale tra le seguenti coppie di numeri (x, y) è soluzione del sistema:\nx + y = 10\nx - y = 4", options: ["(5, 5)", "(8, 2)", "(6, 4)", "(7, 3)"], correctAnswerIndex: 3, explanation: "Sommando le equazioni: 2x = 14 => x = 7. Sostituendo nella prima: 7 + y = 10 => y = 3. Soluzione (7, 3)." },
  { id: 'mat-10-add-16', type: QuestionType.MULTIPLE_CHOICE, topic: 'Numeri', text: "Un libro è venduto con sconto del 20%. Il prezzo scontato è 72 €. Qual era il prezzo iniziale?", options: ["86,4 €", "90 €", "92 €", "57,6 €"], correctAnswerIndex: 1, explanation: "Se x è il prezzo iniziale, dopo lo sconto resta l’80%, cioè 0,8x. Quindi 0,8x = 72 => x = 72/0,8 = 90 €." },
  { id: 'mat-10-add-17', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Un pannello espositivo è formato da 3 cartelli affiancati. In ciascun cartello la parte stampata è larga x cm e ci sono due bordi laterali da 1 cm (uno a sinistra e uno a destra). Tra un cartello e il successivo c’è uno spazio di 2 cm. La larghezza totale dell’allestimento è 94 cm. Quanto vale x?", options: ["26 cm", "28 cm", "29 cm", "30 cm"], correctAnswerIndex: 1, explanation: "Ogni cartello occupa (x + 2) cm. Tre cartelli occupano 3(x + 2). Ci sono due spazi da 2 cm tra i cartelli (+4). Eq: 3(x + 2) + 4 = 94 => 3x + 6 + 4 = 94 => 3x = 84 => x = 28." },
  { id: 'mat-10-add-18', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Il margine economico (in euro) di un’attività, in funzione del prezzo x (in euro) fissato per un prodotto, è modellizzato da M(x) = (x - 2)(10 - x). Per quali valori di x il margine è non negativo (M(x) ≥ 0)?", options: ["x ≤ 2 oppure x ≥ 10", "2 ≤ x ≤ 10", "x < 2", "x > 10"], correctAnswerIndex: 1, explanation: "Studiamo il segno dei fattori: (x-2) ≥ 0 per x ≥ 2; (10-x) ≥ 0 per x ≤ 10. Il prodotto è positivo nell'intervallo interno 2 ≤ x ≤ 10." },
  { id: 'mat-10-add-19', type: QuestionType.MULTIPLE_CHOICE, topic: 'Numeri', text: "In un laboratorio possono entrare al massimo 28 persone. Ci saranno sempre 3 adulti (docente e assistenti). Gli studenti lavorano in gruppi da 5. Si vuole che partecipino almeno 15 studenti. Se x è il numero di gruppi di studenti, quali sono i possibili valori interi di x?", options: ["{1, 2, 3, 4, 5}", "{3, 4, 5}", "{4, 5, 6}", "{3, 4, 5, 6}"], correctAnswerIndex: 1, explanation: "Persone totali: 5x + 3 ≤ 28 => 5x ≤ 25 => x ≤ 5. Minimo studenti: 5x ≥ 15 => x ≥ 3. Valori interi ammissibili: {3, 4, 5}." },
  { id: 'mat-10-add-20', type: QuestionType.MULTIPLE_CHOICE, topic: 'Numeri', text: "Una misura è -1,75 (ad esempio, un dislivello di m rispetto al livello 0). Quale frazione rappresenta esattamente questo valore?", options: ["-7/4", "-4/5", "-5/7", "-2/3"], correctAnswerIndex: 0, explanation: "-1,75 equivale a -175/100. Semplificando per 25 si ottiene -7/4." },
  { id: 'mat-10-add-21', type: QuestionType.MULTIPLE_CHOICE, topic: 'Spazio e figure', text: "In una mappa su piano cartesiano una strada è descritta da r: y = -1/2x + 3. Una pista ciclabile deve essere parallela a r e passare per il punto P(4, 0). Qual è l’equazione della pista ciclabile?", options: ["y = -1/2x + 2", "y = 1/2x + 2", "y = -2x + 2", "y = -1/2x + 3"], correctAnswerIndex: 0, explanation: "Parallela significa stesso coefficiente angolare m = -1/2. L'equazione è y = -1/2x + q. Sostituendo P(4,0): 0 = -1/2(4) + q => 0 = -2 + q => q = 2. Quindi y = -1/2x + 2." },
  { id: 'mat-10-add-22', type: QuestionType.MULTIPLE_CHOICE, topic: 'Spazio e figure', text: "In una pianta, un corridoio è rappresentato dalla retta verticale x = 3. Un secondo corridoio deve essere perpendicolare a x = 3 e passare per P(1, 4). Qual è la sua equazione?", options: ["y = 4", "x = 4", "y = 3", "x = 3"], correctAnswerIndex: 0, explanation: "Una retta perpendicolare a una retta verticale (x = k) è una retta orizzontale (y = h). Poiché passa per P(1, 4), l'ordinata è costante e vale 4. Equazione: y = 4." },
  { id: 'mat-10-add-23', type: QuestionType.MULTIPLE_CHOICE, topic: 'Spazio e figure', text: "Due antenne sono nei punti A(-2, 1) e B(4, 5). Si vuole individuare la retta che rappresenta il luogo dei punti equidistanti da A e B: è l’asse del segmento AB. Qual è l’equazione dell’asse di AB?", options: ["y = -3/2x + 9/2", "y = 3/2x + 7/3", "y = 3/2x + 3/2", "y = -2/3x + 11/3"], correctAnswerIndex: 0, explanation: "Punto medio M = ((-2+4)/2, (1+5)/2) = (1, 3). Pendenza m_AB = (5-1)/(4-(-2)) = 4/6 = 2/3. Pendenza asse m_perp = -3/2. Retta per M(1,3) con m=-3/2: y - 3 = -3/2(x - 1) => y = -3/2x + 3/2 + 3 => y = -3/2x + 9/2." },
  { id: 'mat-10-add-24', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Risolvi la disequazione (x - 3) / (x + 1) > 0.", options: ["x < -1 oppure x > 3", "-1 < x < 3", "x < -1 oppure x ≥ 3", "x ≤ -1 oppure x > 3"], correctAnswerIndex: 0, explanation: "Numeratore > 0 per x > 3. Denominatore > 0 per x > -1. Il rapporto è positivo quando N e D sono concordi: x > 3 (entrambi positivi) oppure x < -1 (entrambi negativi)." },
  { id: 'mat-10-add-25', type: QuestionType.MULTIPLE_CHOICE, topic: 'Relazioni e funzioni', text: "Per una raccolta fondi la classe vende quaderni (q) e penne (p). Vincoli: 1) Incasso almeno 35 € (3q + 2p ≥ 35); 2) Max 13 oggetti (q + p ≤ 13); 3) Max 9 quaderni (q ≤ 9). Quale coppia (q, p) rispetta tutti i vincoli?", options: ["(8, 5)", "(9, 4)", "(10, 3)", "(7, 6)"], correctAnswerIndex: 1, explanation: "Verifichiamo (9, 4): Totale oggetti 9+4=13 (≤13 OK). Quaderni 9 (≤9 OK). Incasso 3(9)+2(4) = 27+8 = 35 (≥35 OK). Le altre opzioni violano almeno un vincolo." }
];